### ISSUE TITLE
add function has_column ( NAME, NAME, NAME )

### ISSUE THREAD

**Issue by srghma** [theory/pgtap#184]
```
-- has_column( schema, table, column )
CREATE OR REPLACE FUNCTION has_column ( NAME, NAME, NAME )
RETURNS TEXT AS $$
    SELECT ok( _cexists( $1, $2, $3 ), 'Column ' || quote_ident($1) || '.' || quote_ident($2) || '.' || quote_ident($3) || ' should exist' );
$$ LANGUAGE SQL;
```

**Comment by theory** [comment]
Trouble is, there is already a function with that signature:

``` pgsql
-- has_column( table, column, description )
CREATE OR REPLACE FUNCTION has_column ( NAME, NAME, TEXT )
RETURNS TEXT AS $$
    SELECT ok( _cexists( $1, $2 ), $3 );
$$ LANGUAGE SQL;
```

How would we coax Postgres to recognize it was one vs. the other?

**Comment by srghma** [comment]
Hi, i resolved this by adding explicit type signatures. I'm calling my function `has_column( "schema" :: name, "table" :: name, "column" :: name )`

Yes, adding this function would break existing code because the signature would become required

**Comment by theory** [comment]
Yeah, I'm not keen on breaking existing tests, even though I am generally in favor of supporting all the signatures I can. It's fine to require casts and document it if they're there from the start, but `has_column()` has been around since near the beginning; adding the new variant would break a lot of tests and cause unnecessary headaches for people.

Might be nice to rethink some stuff in pgTAP, though, to make it easier to make breaking changes like this without breaking people's tests. Alas, I don't have the TUITs to work on such a thing ATM.

**Comment by srghma** [comment]
@theory what do you think about adding postfix `_d` to name of all function that have description argument

now

```
has_column ( tmth, tmth )
has_column ( tmth, tmth, description)
```

expected

```
has_column ( tmth, tmth )
has_column_d ( tmth, tmth, description)
```

**Comment by srghma** [comment]
Your suggestion is much better :+1:
