### ISSUE TITLE
Parallel testing with fixtures

### ISSUE THREAD

**Issue by dvasdekis** [theory/pgtap#267]
Hey folks!

What would be the right way to test in parallel with setup fixtures?

I am thinking about something that will:
1. Run my test in a separate isolated database using `CREATE DATABASE my_new_database TEMPLATE my_old_database;` (as a substitute for `BEGIN; ROLLBACK;` capability which would be unavailable across multiple transactions)
2. Execute `runtests()` using the new database, with each stage run in parallel (with connections = function count for that stage)
3. Emit the test output
4. Drop the newly created database

Am I missing anything here? This would be a pretty simple job to whip up in Python, and I'm happy to do it. I'm just wondering why this doesn't yet exist/isn't built into pg_prove already (which is phenomenal as-is! don't get me wrong!)

Thoughts?

**Comment by dvasdekis** [comment]
To be honest I haven't tried it, but don't you say that yourself in the
docs? ("All runtests() functions will run in a single transaction")

**Comment by theory** [comment]
Yes, you're right, that's what the docs say. I think the simplest way to get parallelism is to create multiple test scripts, each of which runs a discrete subset of the tests, then use `pg_prove -j` to run them all. Would be interesting to think about how one might do it in `pg_prove` itself, but I don't think it can be done in pgTAP. Have you tried your approach with Python? Curious how it turned out.
