### ISSUE TITLE
pg_prove: Cannot determine source for --source

### ISSUE THREAD

**Issue by lifepillar** [theory/pgtap#81]
When I execute `pg_prove` as follows:

    pg_prove -d testdb test.sql

with this minimal `test.sql` script:

```sql
begin;
select plan(1);
select pass( 'My test passed, w00t!' );
select * from finish();
rollback;
```

I get the following error:

```
test.sql .......... Bareword found where operator expected at test.sql line 4, near "* from finish"
	(Missing operator before finish?)
syntax error at test.sql line 4, near "* from finish"
Execution of test.sql aborted due to compilation errors.
test.sql .......... Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run 
Cannot determine source for --source at /System/Library/Perl/5.12/App/Prove.pm line 496
```

Running with `--dry` gives the following output:

```
test.sql
--source
pgTAP
--pgtap-option
dbname=testdb
```

This is with pgTap 0.94.0, `pg_prove` 3.29, installed with Homebrew  under OS X, perl 5, version 12, subversion 3 (v5.12.3) built for darwin-thread-multi-2level.

**Comment by lifepillar** [comment]
In fact, just running `pg_prove` without any arguments results in

```
Cannot determine source for --source at /System/Library/Perl/5.12/App/Prove.pm line 496
```

**Comment by theory** [comment]
Sounds like it thinks it’s Perl code, not SQL. Odd since it properly identifies the source as pgTAP. I haven’t seen this issue (not recently, anyway), so can’t replicate it to fix it. I’m also away at a conference. If you are not able to diagnose it by the time I return next week, if you can give me login to a box exhibiting the issue, I can try to diagnose it.

**Comment by lifepillar** [comment]
I've nailed it: I just had an outdated version of `App::Prove` in Perl's library path.
